[package]
name = "topo"
version = "0.1.0"
edition = "2021"

[dependencies]
bao = "0.13"
blake3 = "1"
chacha20poly1305 = "0.10"
crux_core = "0.17.0"
ed25519-dalek = "2"
hkdf = "0.12"
rand_core = { version = "0.6", features = ["getrandom"] }
rusqlite = { version = "0.31", features = ["bundled"] }
sha2 = "0.10"
x25519-dalek = { version = "2", features = ["static_secrets"] }

[dev-dependencies]
tempfile = "3"
